### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by asheshambasta** [ConferHealth/composite#26]
I'm sorry for opening an issue for asking a question. However, are there any future prospects of maintaining this library for newer versions of GHC? As of now, I'm unable to compile this with GHC 8.6.*. 

Any updates will be helpful.

**Comment by Dridus** [comment]
Hello! Confer has dissolved and so there is nobody working on this for money there. That said, I'll gladly accept pull requests. In general I'm pretty busy so I don't have free time right now to do the update myself. @asariley @mjrussell @dfithian maybe?

**Comment by dfithian** [comment]
Not up to date with Nix but could presumably do the stack and hpack parts. I think in order to do so I'd need to be a maintainer in Hackage (username dfithian). Are these packages supported in Stackage?

**Comment by Dridus** [comment]
@dfithian they're not in stackage right now, no. I think they're closer to being acceptable for stackage than they used to be, but I forget what was the sticking point I didn't want to fix at the time.

I'll add you as a maintainer.

**Comment by asheshambasta** [comment]
Okay, thanks for clarifying @Dridus. I'll see if I can come up with a quick PR this weekend if my schedule allows for it. 
In case it is of any help, here's the logs: https://gist.github.com/asheshambasta/6332516ba31e987e28b25787644d9de6

If I can be of any help, please let me know.

**Comment by dfithian** [comment]
@asheshambasta can you try with the PR I put up?

**Comment by asheshambasta** [comment]
@dfithian I'm afraid it still doesn't compile at `15b8aa2161de2839cce94ef1eae42d48bbb76b14`
Logs: https://gist.github.com/asheshambasta/071e52cb78c73297d0f06ff2a7982509

**Comment by dfithian** [comment]
@asheshambasta I think that's the first commit in the sequence, can you try with the latest or just check out the branch?

**Comment by asheshambasta** [comment]
@dfithian thanks, yeah that was my bad. Yeah, looks like things compile as expected with the stackage `lts-14.3`.

Thanks a lot!

**Comment by dfithian** [comment]
Released: http://hackage.haskell.org/package/composite-base
