### ISSUE TITLE
Docs failing for 0.7.2.0

### ISSUE THREAD

**Issue by locallycompact** [ConferHealth/composite#34]
https://hackage.haskell.org/package/composite-aeson-0.7.2.0/reports/3

**Comment by Dridus** [comment]
this seems to be due to hackage building with a combination of versions that is more like stackage nightly than LTS 16, so the 8.10 version should fix this up. working on fixing a bunch of -Werror things there then will do

**Comment by Dridus** [comment]
0.7.3.0 tagged and uploaded, which hopefully will fix this. @locallycompact please close this if it does
