### ISSUE TITLE
8.10 compatible release

### ISSUE THREAD

**Issue by locallycompact** [ConferHealth/composite#35]
Hi could we put out a version for this?

**Comment by Dridus** [comment]
yep, in the middle of fixing up the doc issue, which is essentially the same as this one

**Comment by Dridus** [comment]
k, 0.7.3.0 tagged and uploaded. please close this if it works for you @locallycompact

**Comment by locallycompact** [comment]
Looks good. It seems vinyl has been kicked out of stack nightly for some reason but when it comes back I'll add these to stackage.
