### ISSUE TITLE
NFData, Hashable, Binary Instances

### ISSUE THREAD

**Issue by locallycompact** [ConferHealth/composite#36]
Hi, these aren't dependencies of composite so I was planning on making orphan packages for all of these three (since they're need for Shake), unless you'd consider any of these potentially in-scope of composite-base and wanted to include a dependency - 
They look like this.

```
instance Hashable a => Hashable (s :-> a) where
  hashWithSalt n x = hashWithSalt n $ getVal x

instance Binary a => Binary (s :-> a) where
  put = put . getVal
  get = fmap (runIdentity . val) get

instance NFData (s :-> a) where
  rnf x = seq x ()
  
instance Binary (Record '[])
 
instance (Binary a, Binary (Record xs), x ~ (s :-> a)) => Binary (Record (x : xs)) where
  put (x :*: xs) = put x >> put xs
  get = liftA2 (:*:) get get

instance NFData (Record '[]) where
  rnf RNil = ()

instance (NFData a, NFData (Record xs), x ~ (s :-> a)) => NFData (Record (x : xs)) where                 
  rnf (x :*: xs) = rnf x `seq` rnf xs

instance Hashable (Record '[]) where
  hashWithSalt n RNil = n `hashWithSalt` ()

instance (Hashable a, Hashable (Record xs), x ~ (s :-> a)) => Hashable (Record (x : xs)) where
  hashWithSalt n (x :*: xs) = n `hashWithSalt` x `hashWithSalt` xs
```

**Comment by Dridus** [comment]
yeah I'd add them as packages with orphans, ala composite-aeson-refined

**Comment by locallycompact** [comment]
Cool, closing.

**Comment by Dridus** [comment]
could leave this open and add them as a separate package?

**Comment by locallycompact** [comment]
Ok sure. All three in `composite-orphans` or?

**Comment by Dridus** [comment]
`deepseq` is packed with GHC actually so that can go in `composite-base` and the dep added.
for the other two, I'd prefer separate packages - `composite-hashable` and `composite-binary`

**Comment by Dridus** [comment]
done in #39
