### ISSUE TITLE
Hackage doc missing `@`

### ISSUE THREAD

**Issue by rinn7e** [ConferHealth/composite#46]
Not sure if this is known already or not but it seems like the doc in hackage is missing `@` in the example:
- Supposed to be `val @"foo" 123` instead of `val "foo" 123`
Link to hackage: https://hackage.haskell.org/package/composite-base-0.7.4.0/docs/Composite-Record.html

![image](https://user-images.githubusercontent.com/8400953/107111282-65079e00-6881-11eb-9550-0c2506b129a2.png)

**Comment by Dridus** [comment]
nice catch, thanks!
