### ISSUE TITLE
Version bounds on profunctors is too strict

### ISSUE THREAD

**Issue by sternenseemann** [ConferHealth/composite#50]
* composite-aeson
* composite-base
* composite-opaleye

restrict `profunctors` to `< 5.6`, but compile fine with 5.6.2 (couldn't test `composite-opaleye` due to #48).

**Comment by Dridus** [comment]
okay, loosened the bound. didn't test it though, so taking your word for it

**Comment by sternenseemann** [comment]
Revised cabal files on hackage would be neat as well!
