### ISSUE TITLE
Link to composite-dhall

### ISSUE THREAD

**Issue by locallycompact** [ConferHealth/composite#53]
So I got this working in the last few days. Would you mind linking to it in the README?

https://hackage.haskell.org/package/composite-dhall

**Comment by Dridus** [comment]
nice! I see you also have several other composite themed libraries up on hackage, you want to have links to those as well?

**Comment by locallycompact** [comment]
Sure, thanks! The ones I think are either actually useful or interesting are composite-tuple, polysemy-methodology-composite and compdoc. The rest are probably noise. I'm not sure.

**Comment by Dridus** [comment]
alright, updated. let me know if you have any changes or such!

thanks again for your continued help :-)
