### ISSUE TITLE
Can we release composite independently of the other projects?

### ISSUE THREAD

**Issue by locallycompact** [ConferHealth/composite#58]
Hi. I don't use any of the other projects in this repository and it's annoying to have to upgrade things like [ekg-json](https://github.com/tibbe/ekg-json/pull/12) for a hackage release of the core library. It's blocking adoption of composite in other areas with there not being a ghc 9.2 release available. Can composite have its own repository for the core functionality?

**Comment by Dridus** [comment]
I'm not opposed. if we had separate repos then probably we'd want a dedicated organization. we could also tick the versions of things in the repo unevenly.

**Comment by locallycompact** [comment]
Can we get a new tick of composite-base since I believe master is 9.2 compatible now.

**Comment by Dridus** [comment]
@dfithian do you have time to do this sometime next week, by chance? I'm flat out

**Comment by dfithian** [comment]
I’ll take care of it this weekend.

You want me to create an organization for composite and repos for each package?

**Comment by Dridus** [comment]
sure, if you want to go for the full thing! the smaller thing would be just a point release of the things that build on GHC 9.2 (base, aeson?)

**Comment by dfithian** [comment]
There's not currently a tag for v0.7.5.0, though it is on hackage.

I think this was the last change to be added: https://github.com/ConferOpenSource/composite/pull/47

Edit: there's also no changelog entry for it.

**Comment by dfithian** [comment]
https://hackage.haskell.org/package/composite-base-0.7.6.0

**Comment by dfithian** [comment]
And here's the rest: https://github.com/ConferOpenSource/composite/pull/59

**Comment by locallycompact** [comment]
Thanks so much!

**Comment by dfithian** [comment]
Closing this for now. Working on setting up new repositories.
